# Generated by Django 5.2.11 on 2026-05-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='capacity',
            field=models.PositiveIntegerField(default=0, help_text='0 means unlimited'),
        ),
    ]
